name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install gtest
        uses: actions/checkout@v2
        with:
          repository: google/googletest
          ref: refs/tags/release-1.11.0
          path: googletest
      - run: cmake -DCMAKE_BUILD_TYPE=Release -DGTEST_ROOT=googletest/googletest -DGMOCK_ROOT=googletest/googlemock .
      - run: make
      - run: make check
